name: Cheff application build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    name: cheff deploy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17' 
          distribution: 'temurin'
          cache: maven
      - name: Build cheff app
        run: mvn -B clean compile package
        
#     Set global environment variables:
      - name: set global env
        id: global_env
        run: |
          echo "::set-output name=CHEFF_APP::${GITHUB_REPOSITORY#*/}"
          echo "::set-output name=DOCKERHUB_CHEFF_APP::docker.pkg.github.com/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY#*/}"

#     Build Docker image:
      - name: Build and tag image
        run: |
          docker build --tag "${{ steps.global_env.outputs.DOCKERHUB_CHEFF_APP }}:latest" --tag "${{ steps.global_env.outputs.DOCKERHUB_CHEFF_APP }}:${GITHUB_SHA::8}" .

      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.CHEFF_CI}}

#     Publish image to github package repository:
      - name: Publish image
        env:
          IMAGE_NAME: $GITHUB_REPOSITORY
        run: docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/${{ steps.global_env.outputs.CHEFF_APP }}"
        
