name: Cheff application build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install
        run: mvn install
        
      - name: Compile
        run: npm compile

      - name: Deploy
        run: npm deploy

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.CHEFF_CI }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
